language: node_js
node_js:
  - '12'
env:
  - CODECOV_TOKEN="07cf711c-3342-4b4d-abe3-4d98f8a1a8f69"
cache:
  directories:
    - $HOME/.npm
script:
  - npm test
  - npm run test:report && codecov
  - npm run cy:ci  && codecov
  - npm run build
after-script:
  - bash <(curl -s https://codecov.io/bash)
