codecov:
  token: 07cf711c-3342-4b4d-abe3-4d98f8a1a8f6

# configuration related to pull request comments

coverage:
  status:
    project: # settings affecting project coverage
      default:
        target: auto # auto % coverage target
        threshold: 20% # allow for 5% reduction of coverage without failing

    # do not run coverage on patch nor changes
    patch: false
